---
- name: Install VDA Pre-Reqs
  win_feature:
    name:
    - NET-Framework-45-Core
    - Telnet-Client
    - RDS-RD-Server
    - Remote-Assistance
    state: present
  register: win_feature

- name: Reboot if features require
  win_reboot:
  when: win_feature.reboot_required

- name: Create Log Folder
  win_file:
    path: C:\Logs
    state: directory

- name: Map SMB share
  win_shell: |
    net use \\10.10.1.18 "deviceTRUST$" /user:share

- name: Install VDA Components
  win_package:
    path: "{{ citrix_sources_path }}\\x64\\XenDesktop Setup\\XenDesktopVdaSetup.exe"
    arguments: /quiet /optimize /components vda /controllers '{{ citrix_site_DDC }}' /enable_remote_assistance /enable_hdx_ports /enable_real_time_transport /virtualmachine /noreboot /noresume /logpath 'C:\Logs' /masterimage
    state: present
    expected_return_code: [0, 3, 3010]
    creates_service: BrokerAgent
  register: vda_install

- name: Reboot after VDA
  win_reboot:
  when: vda_install.changed
