---
- name: Update PowerShell help content
  ansible.windows.win_powershell:
    script: |
      update-help

- name: Create files directory
  ansible.windows.win_file:
    path: c:\files
    state: directory

- name: Copy wallpaper to files directory
  ansible.builtin.copy:
    src: files/dT_Wallpaper.png
    dest: c:\files\dT_Wallpaper.png