---
- name: Install prerequisites
  become: true
  shell: |
    apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common \
    git \
    docker \
    docker-compose \
    docker.io

- name: Remove old data
  become: true
  file:
    path: /home/vagrant/git/
    state: absent

- name: Create GIT folder
  become: true
  file:
    path: /home/vagrant/git/
    state: directory

- name: Clone github repository
  become: true
  shell: |
    cd /home/vagrant/git/
    git clone "https://github.com/deviceTRUST/democloud-docker-guacamole.git"

- name: Stop Docker container
  become: true
  shell: |
    cd /home/vagrant/git/democloud-docker-guacamole
    docker-compose rm --stop --force

- name: Install 2-FA TOTP extension for Guacamole 
  become: true
  shell: |
    tar xvf /home/vagrant/git/democloud-docker-guacamole/guac_home/extensions/guacamole-auth-totp-1.4.0.tar.gz -C /home/vagrant/git/democloud-docker-guacamole/guac_home/extensions
    mv -f /home/vagrant/git/democloud-docker-guacamole/guac_home/extensions/guacamole-auth-totp-1.4.0/guacamole-auth-totp-1.4.0.jar /home/vagrant/git/democloud-docker-guacamole/guac_home/extensions/.
    rm -rf /home/vagrant/git/democloud-docker-guacamole/guac_home/extensions/guacamole-auth-totp-1.4.0 /home/vagrant/git/democloud-docker-guacamole/guac_home/extensions/guacamole-auth-totp-1.4.0.tar.gz
    chmod 777 /home/vagrant/git/democloud-docker-guacamole/guac_home/extensions/guacamole-auth-totp-1.4.0.jar
    chown root:root /home/vagrant/git/democloud-docker-guacamole/guac_home/extensions/guacamole-auth-totp-1.4.0.jar

- name: Create Docker container
  become: true
  shell: |
    cd /home/vagrant/git/democloud-docker-guacamole
    sudo docker-compose up -d