---
# Ansible variables
ansible_user: vagrant
ansible_password: vagrant

# Domainjoin variables
domainjoin_domain_name: dt.training
domainjoin_user_pw: ThisIsASecurePassword!2022
domainjoin_user_name: svc_domainjoin@dt.training
domainjoin_ou: 'OU=Computer,OU=Objects,DC=dt,DC=training'