---
ansible_user: admin
ansible_password: Passw0rd
ansible_port: 5986
ansible_connection: winrm
# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore

# nic_register_dns_disabled: Ethernet
win_user_language: de-DE
dns_client_configure: True
dns_client_adapter: Ethernet
dns_client_dns_server_ip: 10.10.11.10

# Language settings variable
config_system_locale: 'de_DE.UTF-8'
config_system_language: 'en_US.UTF-8'