---
# Guac global
guac_mfa_enabled: "false"

# Docker
docker_host_subnet_base: 172.73.0.0/16
docker_host_subnet_size: 24
docker_host_bridge_ip: 172.29.0.1/16
docker_container_volume_base_dir: /srv/docker_data

# Docker container traefik
docker_container_traefik_name: traefik
docker_container_traefik_image: "traefik" #:v2.6"
docker_container_traefik_network_name: "{{ docker_container_traefik_name }}_proxy_net"
docker_container_traefik_network_subnet: "{{ docker_host_subnet_base | ansible.utils.ipsubnet(24, 7) }}"
docker_container_traefik_network_gateway: "{{ docker_container_traefik_network_subnet | ansible.utils.ipaddr('next_usable') }}"
docker_container_traefik_le_acme_email: "postmaster@{{ public_hosting_domain }}"
docker_container_traefik_volume_dir: "{{ docker_container_volume_base_dir }}/{{ docker_container_traefik_name }}"
docker_container_traefik_entrypoints_trustedips: "127.0.0.1/32, {{ '/'.join((ansible_default_ipv4.network, ansible_default_ipv4.netmask))  | ansible.utils.ipaddr('net') }}"
docker_container_traefik_traefik_rule: "Host(`traefik.{{ public_hosting_domain }}`)"

docker_container_traefik_certdumper_name: certdumper
docker_container_traefik_certdumper_image: "ldez/traefik-certs-dumper:v2.7.0"

# Docker container guac
docker_container_guac_version: 1.4.0
docker_container_guac_name: guac
docker_container_guac_image: "guacamole/guacamole"

docker_container_guac_d_name: guacd
docker_container_guac_d_image: "guacamole/guacd"

docker_container_guac_db_name: guac-db
docker_container_guac_db_image: "mysql"

docker_container_guac_volume_dir: "{{ docker_container_volume_base_dir }}/{{ docker_container_guac_name }}"
docker_container_guac_traefik_rule: "Host(`guac.{{ public_hosting_domain }}`)"

guac_mfa_enabled: '{{ guac_mfa_enabled }}'

guac_db_name: 'guacamole'
guac_db_user: 'guacdbadmin'
guac_db_password: 'ThisIsASecurePassword!2022'
guac_db_root_password: 'ThisIsASecurePassword!2022'

guac_ldap_admin_user: 'vagrant'
guac_ldap_admin_group: 'g_g_sec_guac_admins'
guac_root_connection_group: 'some-ou'
guac_initial_connection_name: 'initial-connection'
guac_initial_connection_hostname: 'initial-hostname'