---
win_user_language: de-DE

dns_client_configure: True
dns_client_adapter: Ethernet
dns_client_dns_server_ip: 10.10.11.10

install_rds_licensing: true
rds_licensing_mode: 4
rds_licening_server_name: localhost
remotedesktopuser_group_name: Remote Desktop Users
members_of_remotedesktopuser:
  - '{{ domain_netbios_name }}\Domain Users'