---
# Ansible variables
ansible_user: vagrant
ansible_password: ThisIsASecurePassword!2022

# DNS Configuration
dc_dns_upstream: 10.10.11.1
dc_dns_zone_name: dt.training

# NTP Configuration
dc_ntp_servers: 0.us.pool.ntp.org,1.us.pool.ntp.org

# OUs
dc_ou_user_standard: OU=User,OU=Accounts,OU=Objects,DC=dt,DC=training
dc_ou_user_admin: OU=Admins,OU=Accounts,OU=Objects,DC=dt,DC=training
dc_ou_user_service: OU=Services,OU=Accounts,OU=Objects,DC=dt,DC=training

# Passwords
dc_password_admin: ThisIsASecurePassword!2022
dc_password_user: deviceTRUST!2022
dc_password_service: ThisIsASecurePassword!2022
dc_password_safemode: ThisIsASecurePassword!2022

# Users
dc_user_admin: administrator@dt.training
domain_ou_base: DC=dt,DC=training
domain_ou_objects: OU=Objects,DC=dt,DC=training
domian_ou_training: ['OU=Training01']

domain_ous:
  - { name: 'Objects', path: '{{ domain_ou_base }}' }

# OUs
dc_ou:
  - name: Objects
    path: '{{ domain_ou_base }}'
  - name: Training01
    path: '{{ domain_ou_objects }}'
  - name: Accounts
    path: '{{ domian_ou_training }}'
  - name: Computer
    path: '{{ domian_ou_training }}'
  - name: Groups
    path: '{{ domian_ou_training }}'
  - name: 02_Administration
    path: OU=Computer,'{{ domian_ou_training }}'
  - name: 03_Environment
    path: OU=Computer,'{{ domian_ou_training }}'
  - name: 04_Endpoints 
    path: OU=Computer,'{{ domian_ou_training }}'
  - name: FatClient
    path: OU=03_Environment,OU=Computer,'{{ domian_ou_training }}'
  - name: RDSH
    path: OU=03_Environment,OU=Computer,'{{ domian_ou_training }}'
  - name: User
    path: OU=Accounts,'{{ domian_ou_training }}'
  - name: Services
    path: OU=Accounts,'{{ domian_ou_training }}'
  - name: Admins
    path: OU=Accounts,'{{ domian_ou_training }}'

# Groups
dc_groups:
  - name: g_g_sec_citrix_users
    scope: global
    path: 'OU=Groups,OU=Objects,DC=dt,DC=training'
  - name: g_g_sec_guac_admins
    scope: global
    path: 'OU=Groups,OU=Objects,DC=dt,DC=training'

# Users
dc_user_standard: [training]
dc_user_service: [svc_domainjoin,svc_ldap]

dc_groupmember:
  - name: training
    group: g_g_sec_citrix_users