---
ansible_user: localadmin
ansible_password: S00perSecurePassw0rd2023
ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore
ansible_port: 5985

sw_dt_version: '23.1.100'

win_software_chocolatey: ['7zip','firefox','Notepadplusplus']

# Domain configuration variables
domain_dnsname: dt.training

# Domainjoin variables
domainjoin_domain_name: dt.training
domainjoin_user_pw: S00perSecurePassw0rd2023
domainjoin_user_name: svc_domainjoin@dt.training
domainjoin_ou: 'OU=Computer,OU=Objects,DC=dt,DC=training'

# DNS client variables
dns_client_adapter: Ethernet
dns_client_dns_server_ip: 10