---
ansible_user: admin
ansible_password: Passw0rd
ansible_port: 5986
ansible_connection: winrm
# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore

# nic_register_dns_disabled: Ethernet
win_user_language: de-DE
domain_dns_name: dt.training
domain_netbios_name: DT
domain_admin_user: administrator@dt.training
domain_admin_password: vagrant
dns_client_configure: True
dns_client_adapter: Ethernet
dns_client_dns_server_ip: 10.10.11.10
policy_definitions_dir: C:\Windows\SYSVOL\domain\Policies\PolicyDefinitions

install_rds_licensing: true
rds_licensing_mode: 4
rds_licening_server_name: localhost
remotedesktopuser_group_name: Remote Desktop Users
members_of_remotedesktopuser:
  - '{{ domain_netbios_name }}\Domain Users'