---
- hosts: localhost
  vars_files:
    - ../vars/test.yml

  tasks:
  - name: with_sequence -> loop
    ansible.builtin.debug:
      msg: "{{ 'testuser%02x' | format(item) }}"
    loop: "{{ range(1, '{{ test_count }} + 1, 1) | list }}"