---
- hosts: localhost
  vars_files:
    - ../vars/test.yml
    - ../vars/windows-dc-local.yml

  tasks:
    - name: dingledongel
      ansible.builtin.debug:
        msg: "{{ item.0.name }} - {{ item.0.path }} - {{ item.1 }}"
      with_nested:
        - "{{ dc_ous_static }}"
        - "{{ range(1, 10 + 1, 1) | list }}"