---
- hosts: localhost
  gather_facts: no
  vars:
    ou_path:
      path: "Training{{ item }},{{ domain_ou_objects }}"
    domain_ou_base: DC=dt,DC=training
    domain_ou_objects: 'OU=Objects,{{ domain_ou_base }}'
    test_count: 5
    
  tasks:

    # construct list
    - set_fact:
        ou_pattern: "{{ (ou_pattern | default([])) + [ou_path] }}"
      with_sequence: "start=1 count=5"
    - debug:
        msg: "{{ ou_pattern }}"

    # execute single task, no need in list
    - debug:
        msg: "{{ ou_path }}"
      with_sequence: "start=1 count={{ test_count }}"