---
- hosts: localhost
  vars_files:
    - ../vars/test.yml

  tasks:
  - name: dingledongel
    ansible.builtin.debug:
      msg: "{{ item.0 }} - {{ item.1 }}"
    with_nested:
      - "{{ list_one }}"
      - "{{ range(1, 10 + 1, 1) | list }}"

  - name: repeat
    ansible.builtin.debug:
      msg: "{{ item.0 }} - {{ item.1 }}"
    repeat_original: "{{ [1,2] | product(repeat={{ test_count }}) }}"




      