---
- hosts: localhost
  vars_files:
    - ../vars/test.yml

  tasks:
  - name: with_nested
    ansible.builtin.debug:
      msg: "{{ item.0 }} - {{ item.1 }}"
    with_nested:
      - "{{ list_one }}"
      - "{{ range(1, 10 + 1, 1) | list }}"

  - name: with_nested -> loop
    ansible.builtin.debug:
      msg: "{{ item.0 }} - {{ item.1 }}"
    loop: "{{ list_one|product(list_two)|list }}"