---
- hosts: localhost
  vars_files:
    - ../vars/test.yml
    - ../vars/windows-dc-local.yml

  tasks:
    - name: dingledongel
      ansible.builtin.debug:
        msg: "{{ item.0.name }} - {{ item.0.path | replace('##','Banana') }} - {{ item.1 }} "
      with_nested:
        - "{{ dc_ous_static }}"
        - "{{ range(1, dc_domain_count + 1, 1) | list }}"