---
  - name: Create install directory
    ansible.windows.win_file:
      path: c:\install
      state: directory

  - name: Download deviceTRUST
    ansible.builtin.win_get_url:
      url: https://storage.devicetrust.com/download/deviceTRUST-21.1.310.zip
      dest: c:\install\

  - name: Unzip deviceTRUST
    community.windows.win_unzip:
      src: c:\install\deviceTRUST-21.1.310.zip
      dest: c:\install\deviceTRUST-21.1.310

  - name: Install deviceTRUST Console
    ansible.windows.win_package:
      path: c:\install\deviceTRUST-21.1.310\dtconsole-x64-release-21.1.310.0.msi
      arguments:
        - /quiet
        - /passive
        - /norestart
      state: present
      creates_path: C:\Program Files\deviceTRUST\Console
  
  - name: Install deviceTRUST Agent
    ansible.windows.win_package:
      path: c:\install\deviceTRUST-21.1.310\dtagent-x64-release-21.1.310.0.msi
      arguments:
        - /quiet
        - /passive
        - /norestart
      state: present
      creates_path: C:\Program Files\deviceTRUST\Agent

  - name: Install Printers
    win_shell: |
      if(get-printerdriver -name "Generic / Text Only"){}else{Add-PrinterDriver -Name "Generic / Text Only"}
      if(get-printer -name "Corporate"){}else{Add-Printer -Name "Corporate" -DriverName "Generic / Text Only" -PortName LPT1:}
      if(get-printer -name "Floor 1"){}else{Add-Printer -Name "Floor 1" -DriverName "Generic / Text Only" -PortName LPT2:}
      if(get-printer -name "Floor 2"){}else{Add-Printer -Name "Floor 2" -DriverName "Generic / Text Only" -PortName LPT3:}
    args:
        creates: C:\Logs\done-printer-install.txt

  - name: Reboot
    ansible.windows.win_reboot: