---
- hosts: linux-guacamole
  become: true
  vars_files:
    - vars/linux.yml
    - vars/linux-guacamole.yml

  roles:
    - { role: ansible-role-linux-software-installation }

  tasks:
    - name: Install docker python sdk
      pip:
        name: docker