---
- src: https://github.com/deviceTRUST/ansible-r-win-srv-rdsh-devicetrust
- src: https://github.com/deviceTRUST/ansible-r-win-srv-dc-conf-users
- src: https://github.com/deviceTRUST/ansible-r-win-srv-dc-conf-objects
- src: https://github.com/deviceTRUST/ansible-r-win-srv-dc-gpo-import
- src: https://github.com/deviceTRUST/ansible-r-win-srv-dc-gpo-bind
- src: https://github.com/deviceTRUST/ansible-r-win-srv-dc-devicetrust
- src: https://github.com/deviceTRUST/ansible-r-win-srv-dc-ad-conf-users
- src: https://github.com/deviceTRUST/ansible-r-win-srv-dc-ad-conf-ous
- src: https://github.com/deviceTRUST/ansible-r-win-srv-dc-base
- src: https://github.com/deviceTRUST/ansible-r-win-srv-dc-ad-inst
- src: https://github.com/deviceTRUST/ansible-r-win-srv-dc-ad-conf
- src: https://github.com/deviceTRUST/ansible-r-win-domainjoin
- src: https://github.com/deviceTRUST/ansible-r-win-client-devicetrust
- src: https://github.com/deviceTRUST/ansible-r-win-all-updates
- src: https://github.com/deviceTRUST/ansible-r-win-all-cleanup
- src: https://github.com/deviceTRUST/ansible-r-win-all-chocolatey
- src: https://github.com/deviceTRUST/ansible-r-win-all-base
- src: https://github.com/deviceTRUST/ansible-r-win-srv-dc