---
- hosts: windows-byod

  vars_files:
    - vars/generic.yml
    - vars/windows.yml
    # - vars/windows-byod.yml

  roles:
    # - { role: ansible-role-win-member-dns }
    - { role: ansible-role-win-sw-dt-clientextension }