---
- hosts: windows-rdsh
  ignore_unreachable: true

  vars_files:
    - vars/generic.yml
    - vars/windows.yml
    - vars/windows-rdsh.yml
    
  roles:
    - { role: ansible-role-win-sw-dt-agent }
    - { role: ansible-role-win-sw-dt-clientextension }